name: Test on PR and Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
       swift package clean
       swift package reset
       swift build -v
    - name: Run tests
      run: |
        swift test -v
        bash <(curl -s https://codecov.io/bash)

