name: Publish Documentation
on:
  release:
    types: [published]
jobs:
  deploy_docs:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.JAZZY }}
        config: .jazzy.yaml
